### ISSUE TITLE
공통 Response 포맷 개발

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#1]
## Goal 

공통 Response, Error 포맷 개발

## Reference 

- [Exception Handler 관련 블로깅 ](https://rookedsysc.vercel.app/java-and-spring/spring-boot/exception#basic-global)

## Todo 

- [x] Response 포맷 개발  
- [x] Error Code 포맷 개발 
- [x] Global Exception Handler 적용
