### ISSUE TITLE
CD 방식 변경 - Docker Repository, 메인 서버 변경, 무중단 배포

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#169]
## Goal 

CD 방식 변경 

## Reference 

- 

## Todo 

- [x] Docker Repository에 올려서 배포하는 방식으로 변경
- [x] Local로 메인 서버 변경
- [x] Nginx + Github Actions를 통한 무중단 배포
