### ISSUE TITLE
전적 검색 구현 

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#25]
## Goal 

웹 페이지에서 스크랩핑 해온 데이터를 Redis에 저장

## Reference 

- [AWS Redis 설정시 참고한 Blog](https://velog.io/@ncookie/AWS-ElastiCache-Redis-%EC%A0%81%EC%9A%A9)

## Todo 

- [x] 파이썬으로 전적 검색 사이트 스크랩핑하는 코드 작성
- [x] Spring에서 실행 후 결과 리턴 받기 
- [x] Spring에서 리턴 받은 개체 Redis에 저장

**Comment by rookedsysc** [comment]
## Goal 

요구 조건에 맞춰서 긁어오는 데이터 수정 

## Reference 

- 

## Todo 

- [ ] 게임 아이디 및 모델링 좀 더 상세하게 수정
- [ ] 크롤링 방식에서 API 호출방식으로 변경
