### ISSUE TITLE
Redis, Swagger, Email Dependency 추가 (Rejected)

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#5]
## Goal 

Redis, Swagger, Email Dependency 추가 

## Reference 

- [Swagger 설정시 참조한 Velog](https://hogwart-scholars.tistory.com/entry/Spring-Boot-SpringDoc%EA%B3%BC-Swagger%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-API-%EB%AC%B8%EC%84%9C%ED%99%94-%EC%9E%90%EB%8F%99%ED%99%94%ED%95%98%EA%B8%B0)

## Todo 

- [ ] Redis Dependency 추가 및 Config
- [ ] Swagger Dependency 추가 및 Config
- [ ] Email Dependency 추가 및 Config
