### ISSUE TITLE
Member Entity 변경 (개인정보 처리방침 동의 컬럼 추가)

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#56]
## Goal 

Oauth 특성상 SignUp, SignIn을 따로 구현하기가 어려움 👉 개인정보 처리 방침 동의 했는지 안 했는지에 따라서 권한 나눠야 함 👉 개인정보 처리방침 처리 후 유저 권한 부여

## Reference 

- [Spring Security Official Docs](https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html#match-by-mvc)
- [여러 Role 추가하는 방법에 대해서 상세히 설명해놓은 글](https://velog.io/@goat_hoon/Spring-Security-%EC%9C%A0%EC%A0%80%EC%9D%98-ROLE%EB%B3%84%EB%A1%9C-Authority-%EA%B6%8C%ED%95%9C-%EB%B6%80%EC%97%AC%ED%95%98%EA%B8%B0#2-%EC%9D%BC%EB%B0%98-%EB%A1%9C%EA%B7%B8%EC%9D%B8)

## Todo 

- [x] Database Member Scheme 변경
- [x] 유저 권한 나누기 
- [x] 권한 따라서 Security 접근 가능 API 나누기
- [x] 동의시 동의했음으로 변경하고 ROLE 변경하는 API 추가
- [x] 테스트 코드 작성
