### ISSUE TITLE
Swagger, Spring Security Dependency 추가, Security Config 등록

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#9]
## Goal 

Swagger, Spring Security Dependency 추가, Security Config 등록

## Reference 

- [Swagger 설정시 참조한 Velog](https://hogwart-scholars.tistory.com/entry/Spring-Boot-SpringDoc%EA%B3%BC-Swagger%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-API-%EB%AC%B8%EC%84%9C%ED%99%94-%EC%9E%90%EB%8F%99%ED%99%94%ED%95%98%EA%B8%B0)

## Todo 

- [x] Swagger Depency 추가 
- [x] Spring Security Dependency 추가 
- [x] Swagger, Spring Security Config 등록
