### ISSUE TITLE
테스트 컨테이너 등록 

### ISSUE THREAD

**Issue by rookedsysc** [gamemuncheol/gamemuncheol-api#90]
## Goal 

테스트 방식 H2에서 Test Container 방식으로 변경 

## Reference 

- [우아한 테크코스 테스트 컨테이너 적용기](https://velog.io/@junho5336/TestContainer-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0#testcontainers-container)

## Todo 

- [x] 테스트 컨테이너 디펜던시 등록
- [x] 테스트에서 컨테이너를 활용하기 위한 Abstract Class 정의 
- [x] 테스트 코드에 Abstract Class들 extends
